### ISSUE TITLE
Release assets files still outdated

### ISSUE THREAD

**Issue by thiago-rezende** [julianxhokaxhiu/SteamworksSDKCI#2]
The release asset `SteamworksSDK-v1.51.0_x64.zip` still outdated, without the include files. 
> The build script was already updated on #1 .

**Comment by julianxhokaxhiu** [comment]
You can always find the latest master build here: https://github.com/julianxhokaxhiu/SteamworksSDKCI/releases/tag/canary

Stable releases will be published on every official Steam SDK release.

Cheers!
