### ISSUE TITLE
Instructions are unclear.

### ISSUE THREAD

**Issue by jordan-woyak** [julianxhokaxhiu/SteamworksSDKCI#4]
I'm in exactly the same boat as issue #3.

```
~/projects/steam-input-test/build$ cmake ..
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (STEAMWORKSSDK) does not match the name of the calling package
  (SteamworksSDK).  This can lead to problems in calling code that expects
  `find_package` result variables (e.g., `_FOUND`) to follow a certain
  pattern.
Call Stack (most recent call first):
  SteamworksSDKCI/cmake/FindSteamworksSDK.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find STEAMWORKSSDK (missing: STEAMWORKSSDK_LIBRARY STEAMWORKSSDK_APPTICKET_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jordan/projects/steam-input-test/build
```

Maybe I'm not understanding the purpose of this repository?
I expected to be able to add a git submodule and a few cmake lines to my project and start using SteamworksSDK.
Is that the intention or am I missing something?

I've created a failing attempt here.
https://github.com/jordan-woyak/steam-input-test

**Comment by julianxhokaxhiu** [comment]
Hi,

The idea is that you have two files in the cmake directory:
- [CMakeLists.txt](https://github.com/julianxhokaxhiu/SteamworksSDKCI/blob/master/cmake/CMakeLists.txt): an example CMake file that adds this repository as a dependency in your own cmake file, not mandatory you can integrate it another way
- [FindSteamworksSDK.cmake](https://github.com/julianxhokaxhiu/SteamworksSDKCI/blob/master/cmake/FindSteamworksSDK.cmake): this file will be used by `find_package` when you will require it exactly like you did in your own CMakeLists project example. To know how CMake looks up for this file see https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

CMake has no universal standard way to be used so there's no "simple instructions" to be done here, those are just an example to give a user who already knows how CMake works, how can this project be integrated. But it's not meant to be a copy paste example.

All the best,
Julian

**Comment by jordan-woyak** [comment]
It would be useful to have a copy-paste example for "someone" who doesn't know how to use CMake properly.
It's still unclear to me what's wrong with my testcase at: https://github.com/jordan-woyak/steam-input-test
And this seems like an issue not of my own? `(STEAMWORKSSDK) does not match the name of the calling package (SteamworksSDK)`.
I realize you don't need to cater to CMake noobs but if the intention was to make it easier for others to use SteamworksSDK maybe that's necessary.

**Comment by julianxhokaxhiu** [comment]
No the intention was to provide the Steam SDK as a CMake module, not to make it "easier to use it on CMake". I'm sorry.

Regarding your project, you can try to add:
```cmake
project(steam-input-test VERSION 0.1.0)
list(APPEND CMAKE_MODULE_PATH "SteamworksSDKCI/cmake")
include(SteamworksSDKCI/cmake/CMakeLists.txt)
# ... your code here
```
