### ISSUE TITLE
Wrong naming scheme?

### ISSUE THREAD

**Issue by grappas** [julianxhokaxhiu/SteamworksSDKCI#5]
cmake version 3.23.2

as put everything as is written in README.md i'm getting this error:

`CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindSTEAMWORKSSDK.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "STEAMWORKSSDK", but CMake did not find one.

  Could not find a package configuration file provided by "STEAMWORKSSDK"
  with any of the following names:

    STEAMWORKSSDKConfig.cmake
    steamworkssdk-config.cmake

  Add the installation prefix of "STEAMWORKSSDK" to CMAKE_PREFIX_PATH or set
  "STEAMWORKSSDK_DIR" to a directory containing one of the above files.  If
  "STEAMWORKSSDK" provides a separate development package or SDK, be sure it
  has been installed.`

So instead of:

`find_package(STEAMWORKSSDK REQUIRED)`

I've put something like this:

`find_package(SteamworksSDK REQUIRED)`

and I've got warning:

`CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (STEAMWORKSSDK) does not match the name of the calling package
  (SteamworksSDK).  This can lead to problems in calling code that expects
  `find_package` result variables (e.g., `_FOUND`) to follow a certain
  pattern.
Call Stack (most recent call first):
  cmake/FindSteamworksSDK.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:6 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.`

but cmake parsed with success.

Simply renaming FindSteamworksSDK.cmake to FindSTEAMWORKSSDK.cmake throws this error:

`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find STEAMWORKSSDK (missing: STEAMWORKSSDK_LIBRARY
  STEAMWORKSSDK_APPTICKET_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSTEAMWORKSSDK.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:6 (find_package)
`

**Comment by julianxhokaxhiu** [comment]
Hi,

Actually the way it is works just fine, I'm not sure how your CMake environment is setup but in this other project where we consume this package it works just fine:
- Here you can find an example of [`find_package`](https://github.com/julianxhokaxhiu/FFNx/blob/master/CMakeLists.txt#L79)
- Here you can find a [vcpkg port](https://github.com/julianxhokaxhiu/FFNx/tree/master/.vcpkg/ports/steamworkssdk) that you're free to use if you want

I hope these resources will help you troubleshoot what is going on your own side.

Cheers!

**Comment by julianxhokaxhiu** [comment]
Oh, sorry, I think I found out what is going on. The prefix on the cmake file is not aligned with the file name. My bad! Let me fix it quickly.

**Comment by julianxhokaxhiu** [comment]
Fixed, let me know if it works now!

**Comment by grappas** [comment]
Not exactly:

https://github.com/grappas/WorkshopControl/tree/grappas/sdkcitest

`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SteamworksSDK (missing: SteamworksSDK_LIBRARY
  SteamworksSDK_AppTicket_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  SteamworksSDKCI/cmake/FindSteamworksSDK.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)`

or am I missing something?

**Comment by julianxhokaxhiu** [comment]
Where is [`setup_steamworkssdk()`](https://github.com/grappas/WorkshopControl/blob/grappas/sdkcitest/CMakeLists.txt#L9) defined?

//EDIT: See also https://github.com/julianxhokaxhiu/SteamworksSDKCI/issues/4#issuecomment-1058532313

**Comment by grappas** [comment]
> Where is [setup_steamworkssdk()](https://github.com/grappas/WorkshopControl/blob/grappas/sdkcitest/CMakeLists.txt#L9) defined?

That is on main tree.

Sorry. Haven't pushed new one yet with your module. Try now.

**Comment by julianxhokaxhiu** [comment]
So I took some time to test both your branches:

**master**
All you need to fix is in this diff:
```diff
diff --git a/WorkshopControl.cpp b/WorkshopControl.cpp
index f2be9da..98a3836 100755
--- a/WorkshopControl.cpp
+++ b/WorkshopControl.cpp
@@ -2,7 +2,7 @@
 #include <iostream>
 #include <fstream>
 #include <stdio.h>
-#include "_deps/steamworkssdk-src/include/steam/steam_api.h"
+#include <steam/steam_api.h>^M
 #include <chrono>
 #include <thread>
 #include <getopt.h>
 ```
and here an example build on top of your project:
```sh
➜ make
cmake -DCMAKE_BUILD_TYPE=""Debug"" -S . -B ".build"
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/sbin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dev/projects/github/grappas/WorkshopControl/.build
cmake --build ".build" --config "Debug"
[ 50%] Building CXX object CMakeFiles/WorkshopControl.dir/WorkshopControl.cpp.o
[100%] Linking CXX executable ../bin/Debug/WorkshopControl
[100%] Built target WorkshopControl
```

**grappas/sdkcitest**
Direct import will never work as the project was never meant to be used as a Submodule. As I explained this in here https://github.com/julianxhokaxhiu/SteamworksSDKCI/issues/4#issuecomment-1058138877 you better find your way out to include this project through your build system. I provide the example CMake files just as a commodity.

I highly suggest you to use vcpkg as a CMake package manager, or Conan or similar solutions. If you use vcpkg I also linked to you the port which you can freely make use of if you want to.

This project basically had nothing wrong, it's just basically not giving a hard way to use it, as it's literally up to you to be integrated.

**Comment by jordan-woyak** [comment]
Consider deleting this github repository. Issues #3 #4 and #5 are essentially "How do I use this?". And your response is that we apparently misunderstand the purpose? The existence of this repository confuses people and wastes their time. It's unethical for it to remain public. At least modify the documentation to mention that it's unsuitable for any purpose.

**Comment by julianxhokaxhiu** [comment]
I think it's unethical to tell to someone else what to do on top of their own work, what do you think? If you're in CMake and C++ world you know already what to do and how to integrate it to be honest. And I'm personally using this for another project as a [vcpkg port](https://github.com/julianxhokaxhiu/FFNx/tree/master/.vcpkg/ports/steamworkssdk) so no, won't do it. I'm sorry to disappoint you :)
